### ISSUE TITLE
Cannot get monitors with CLI

### ISSUE THREAD

**Issue by liyan0328** [IBM/newrelic-cli#19]
I have admin access to the NR account and I can see all the monitors in the dashboard, but I am getting errors for both commands below:

$ nr get monitors
Response status code: 401. Get one page monitors, pageSize '50', pageOffset '0'

$ nr get monitor 834b5a8d-367a-4311-8d71-9d5a2db906e6
Enter GetMonitorByID() func, monitor id: 834b5a8d-367a-4311-8d71-9d5a2db906e6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13b2924]

goroutine 1 [running]:
github.com/IBM/newrelic-cli/cmd/get.GetMonitorByID(0x7ffeefbffaf7, 0x24, 0x3, 0x2, 0xc000128060, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/yanli/Downloads/WHC/scripts/src/github.com/IBM/newrelic-cli/cmd/get/get_monitor.go:90 +0x394
github.com/IBM/newrelic-cli/cmd/get.glob..func12(0x197c0a0, 0xc00005d5e0, 0x1, 0x1)
	/Users/yanli/Downloads/WHC/scripts/src/github.com/IBM/newrelic-cli/cmd/get/get_monitor.go:47 +0x5d
github.com/IBM/newrelic-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x197c0a0, 0xc00005d5a0, 0x1, 0x1, 0x197c0a0, 0xc00005d5a0)
	/Users/yanli/Downloads/WHC/scripts/src/github.com/IBM/newrelic-cli/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/IBM/newrelic-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19782e0, 0xc00010ff68, 0x146708e, 0x19782e0)
	/Users/yanli/Downloads/WHC/scripts/src/github.com/IBM/newrelic-cli/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/IBM/newrelic-cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/yanli/Downloads/WHC/scripts/src/github.com/IBM/newrelic-cli/vendor/github.com/spf13/cobra/command.go:800
github.com/IBM/newrelic-cli/cmd.Execute()
	/Users/yanli/Downloads/WHC/scripts/src/github.com/IBM/newrelic-cli/cmd/root.go:57 +0x32
main.main()
	/Users/yanli/Downloads/WHC/scripts/src/github.com/IBM/newrelic-cli/nr.go:20 +0x20

**Comment by liyan0328** [comment]
I figured out the issue myself.  I need to generate and use my own Admin user's API key, Not the API key of the New Relic account.

**Comment by mdminhazulhaque** [comment]
Works for me. Cool.
