### ISSUE TITLE
Update Alert Conditions Fails To Update

### ISSUE THREAD

**Issue by asomensari** [IBM/newrelic-cli#2]
Testing the update alert conditions locally and was not able to update conditions

nr update alertsconditions -f condition.yaml 

returns

Error validating for default type condition "condition.yaml".

I also tried using different types of conditions (nrql, default, synthetics), they all fail.

I will try to debug the code when I have some time too

**Comment by gaochan-1** [comment]
Hi Adilson,

Thanks for your testing and open this issue, I will debug it.

Thanks!

Chan Gao

**Comment by gaochan-1** [comment]
Hi Adilson,

The update alertsconditions cli like this:
`nr update alertsconditions -f <condition.yaml> -t <default|synthetics|ext|plugin|nrql>`

__Note__: The `default` type means `APM` type in condition.

Sample:
`nr update alertsconditions -f condition.yaml -t synthetics`



For the condition.yaml, there are some tips, the condition.yaml file for update should follow this format, like this:
```
synthetics_condition:
  enabled: true
  id: 8790441
  monitor_id: 2ec55438-713a-4d33-bd42-d710c517a1f0
  name: Test Ping
```

I've fixed the bug for this issue, and push latest code to master branch, you can try it again.
If any problem, let me know.


Thanks!

Chan Gao

**Comment by asomensari** [comment]
Thanks Chan!
