### ISSUE TITLE
It starts to back up the monitors but then errors out 

### ISSUE THREAD

**Issue by 6of8Conley** [IBM/newrelic-cli#25]
It starts to back up the monitors but errors out with 

invalid character '<' looking for beginning of value 
Call NewRelic REST error.  

The backup command worked when I ran it on an account with only a few Synthetic checks.  The account I'm trying to back up has 400 tests.

**Comment by EvgenyDos** [comment]
> 429 issue. Too many API requests.

how can I solve it? I cant get list of monitors (about 400 monitors) (bokarevdos@gmail.com)
